### ISSUE TITLE
[-] Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cybrly** [fin3ss3g0d/cypherhound#1]
python3 cypherhound.py -c config.json causes error below.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/8f4b6025-95ec-499f-8b55-30763d6e3f2a">

Steps to reproduce:

- Git clone repo
- Add creds to config.json
- Install requirements.txt
- python3 cypherhound.py -c config.json

**Comment by fin3ss3g0d** [comment]
Should be fixed with f9473b01ceb521e0a8de2bf7735ec17c736615b1
